### ISSUE TITLE
Real Time Device Power Meter

### ISSUE THREAD

**Issue by Sygnus83** [seanblanchfield/smartthings-zipato-rfid#3]
Hi !
Sorry for writing here, but I couldn't write to you anywhere else.
I'm using this : https://seanblanchfield.com/2022/05/real-time-device-power-meters-in-home-assistant

Could you help me with the fact that there is 1 sensor, one TV, which, if it is switched off, is the consumption unavailable...
if I paste this into the type: 'custom:config-template-card' variables , all charts will be black .
If the tv on, all working good.

Thanks in advance if you help !
Greetings: Dani

**Comment by Sygnus83** [comment]
![1](https://user-images.githubusercontent.com/92396929/190899040-995baf84-7106-4aff-862d-93f9cc459496.jpg)
![2](https://user-images.githubusercontent.com/92396929/190899041-61020945-8964-454a-b77b-0c1ed8ab2ee5.jpg)
![3](https://user-images.githubusercontent.com/92396929/190899044-fe9dee49-88a3-4bc0-979c-78e12420c8d5.jpg)

**Comment by seanblanchfield** [comment]
I don't have that problem, because I don't turn off my sensors. But if you need to turn off sensors, you I think you could deal with the resulting "unavailable" state by writing a template sensor that evaluates to 0 when the actual sensor is unavailable, and returns the actual sensor value when it is powered on.
You can learn about template sensors in the HA docs.

**Comment by Sygnus83** [comment]
> I don't have that problem, because I don't turn off my sensors. But if you need to turn off sensors, you I think you could deal with the resulting "unavailable" state by writing a template sensor that evaluates to 0 when the actual sensor is unavailable, and returns the actual sensor value when it is powered on. You can learn about template sensors in the HA docs.


Oh, that's a great idea, I didn't think of it! Thank you!
